language: cpp
os: osx
osx_image: xcode12.5
compiler: clang

before_install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
script:
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cd "./Builds/MacOSX"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then xcodebuild -project Pulverizer.xcodeproj ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO -configuration Release build; fi
- cd ./../.. 

after_success:
- export VERSION=$(git describe --tags)
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then export DEPLOYFILE=Pulverizer-$VERSION.dmg; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mkdir ./output; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then cp -r ./Builds/MacOSX/build/Release/* ./output/; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil create /tmp/tmp.dmg -ov -volname "Pulverizer-$VERSION" -fs HFS+ -srcfolder "./output/"; fi
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then hdiutil convert /tmp/tmp.dmg -format UDZO -o ./$DEPLOYFILE; fi
deploy:
  provider: releases
  api_key:
    secure: "Bx8QQo0fbDxUeHPLmTtEk/qbCK+mC1ajwNb2ag04s76Dqft/a5VmW2RnNFCUF8xss+oZezAng/rO/MO++KYQ4eLH8IPhU5C6VTXAQgMLXPEYA192tQgvFXUwNIPfQJjgDe84TNvhk7ygW5hg5ZTIDql+0a5nKdNM3xBanX0SiakA3tkHRZBIFP6P00aZLhFth6Bm2B/8Dm6AxSYm4po2Xz8PIxcSbQH0Cv2gWEamJEM8qFUeR/cqX7llI85CLukCh6O89/hn4uHW90Fn82JlY84+Uq+6g8NUE8nDN8kPPmGgZ2V8W439tOBtWUwP60UVbskXaszRY9z+hb20TLMKNGDDRi8hekfJY6GUoFkwa5r9Un5tSjzXjqWsDhXjaGf15Ioplmz+rUvS+J4cAtG0MPlR0ntnV5YLI95az/HmImYzlNo7Y56mtCvuhFx1c83cKMH02IkZdAsnejJXH035XPmolYjFYL6K2/A9+mY2yVrSAgDj9iQDJ6D6vtZ+Qsy4x/8lbhZB5DhTD/CHBB8fAnmSsYZ2M5agctmUc7pTuD97auKvi9WkCNbChaZfltgiyZTk5fv1wQLrh6k95kv75QYUKhDnkSn/kfPopERIxotC/CxlDBca3J/zKebIOrhYUYIO3v5EplhXUOCybWjQtmKgJtun0Gb1zxNQpdqkKvo="
    file: "$DEPLOYFILE"
  skip_cleanup: true
  on:
    repo: edgjj/Pulverizer
    tags: true

